export const constants = {
  permissions: [
    "Super_Permission",
    "Admin_Permission",
    "Bill_Admin_Permission",
    "Bill_Permission",
    "Patient_op_Permission",
    "Reporting_Permission",
    "Limited_view",
  ],

  roles: [
    "Super-Admin",
    "Admin",
    "Technologist",
    "Doctor",
    "Nurse",
    "Bill-Officer",
    "User",
  ],

  CPaymentStatus: ["Paid", "Partial", "Unpaid"],
  CPaymentMethod: ["Cash", "Card", "Online"],

  division: ["Laboratory Services", "Radiology & Imaging", "Ultrasonography"],

  department: [
    "Haematology",
    "Biochemistry",
    "Clinical Pathology",
    "Histopathology & Cytopathology",
    "Microbiology",
    "Immunology",
    "Transfusion Medicine",
    "Ultrasonography",
    "Ragiology & Imaging",
  ],

  reportGroup: [
    "CBC",
    "Coagulation",
    "Urine R/M/E",
    "Chemistry",
    "Immunology",
    "Serology",
    "Widal",
    "Blood_Culture",
    "Urine_Culture",
    "Pus_Culture",
    "Stool_Culture",
    "CSF",
    "Histopathology",
    "Cytopathology",
    "Ultrasonography",
    "Ragiology & Imaging",
    "N / A",
  ],

  testSample: [
    "Blood",
    "Urine",
    "Stool",
    "CSF",
    "Plueral Fluid",
    "Ascitic Fluid",
    "Synovial Fluid",
    "Body Tissue",
    "FNAC",
    "Skin Scraping",
    "N / A",
  ],
};
