export const constants = {
  permissions: [
    "Super_Permission",
    "Admin_Permission",
    "Bill_Admin_Permission",
    "Bill_Permission",
    "Patient_op_Permission",
    "Reporting_Permission",
    "Limited_view",
  ],

  roles: [
    "Super-Admin",
    "Admin",
    "Technologist",
    "Doctor",
    "Nurse",
    "Bill-Officer",
    "User",
  ],

  CPaymentStatus: ["Paid", "Partial", "Unpaid"],
  CPaymentMethod: ["Cash", "Card", "Online"],

  division: ["Laboratory Services", "Radiology & Imaging", "Ultrasonography"],

  department: [
    "Haematology",
    "Clinical Pathology",
    "Biochemistry",
    "Immunology",
    "Microbiology",
    "Transfusion Medicine",
    "Histopathology & Cytopathology",
    "Ultrasonography",
    "Radiology & Imaging",
  ],

  reportGroup: [
    "CBC",
    "Coagulation",
    "Urine R/M/E",
    "Biochemistry",
    "Immunology",
    "Serology",
    "Widal",
    "Tripple Antigen",
    "Blood_Culture",
    "Urine_Culture",
    "Pus_Culture",
    "Stool_Culture",
    "Blood Grouping",
    "Compatiblity Test",
    "CSF",
    "Histopathology",
    "Cytopathology",
    "Ultrasonography",
    "Radiology & Imaging",
    "N / A",
  ],

  testSample: [
    "Blood",
    "Urine",
    "Stool",
    "CSF",
    "Plueral Fluid",
    "Ascitic Fluid",
    "Synovial Fluid",
    "Body Tissue",
    "FNAC",
    "Skin Scraping",
    "N / A",
  ],

  reportPaper: {
    height: 11.2,
    width: 8.4,
    headingGap: 1.7,
    footerGap: 0.7,
    // in inch
  },

  reportSampleDepartment: [
    { name: "CBC", department: "Haematology", sample: "Blood" },
    { name: "Coagulation", department: "Haematology", sample: "Blood" },
    { name: "Urine R/M/E", department: "Clinical Pathology", sample: "Urine" },
    { name: "Biochemistry", department: "Biochemistry", sample: "Blood" },
    { name: "Immunology", department: "Biochemistry", sample: "Blood" },
    { name: "CSF", department: "Biochemistry", sample: "CSF" },
    { name: "Serology", department: "Microbiology", sample: "Blood" },
    { name: "Widal", department: "Microbiology", sample: "Blood" },
    { name: "Tripple Antigen", department: "Microbiology", sample: "Blood" },
    { name: "Blood_Culture", department: "Microbiology", sample: "Blood" },
    { name: "Urine_Culture", department: "Microbiology", sample: "Urine" },
    { name: "Pus_Culture", department: "Microbiology", sample: "Pus" },
    { name: "Stool_Culture", department: "Microbiology", sample: "Stool" },
    {
      name: "Blood Grouping",
      department: "Transfusion Medicine",
      sample: "Blood",
    },
    {
      name: "Compatiblity Test",
      department: "Transfusion Medicine",
      sample: "Blood",
    },
    {
      name: "Histopathology",
      department: "Histopathology & Cytopathology",
      sample: "Tissue",
    },
    {
      name: "Cytopathology",
      department: "Histopathology & Cytopathology",
      sample: "Blood",
    },
    { name: "Ultrasonography", department: "Ultrasonography", sample: "Blood" },
    {
      name: "Radiology & Imaging",
      department: "Radiology & Imaging",
      sample: "Blood",
    },
  ],
};
